/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author nacho
 */
public class ArmySelectionWindow extends javax.swing.JFrame {

    /**
     * Creates new form ArmySelectionWindow
     */
    public ArmySelectionWindow() {
        initComponents();
        this.setSize(1370, 780);
        this.setName("Dead Tide");
        
        this.FightHoverLabel.setVisible(false);

        
        this.Warrior1.setOpaque(false);
        this.Warrior1.setContentAreaFilled(false);
        this.Warrior1.setBorderPainted(false);
        this.Warrior2.setOpaque(false);
        this.Warrior2.setContentAreaFilled(false);
        this.Warrior2.setBorderPainted(false);
        this.Warrior3.setOpaque(false);
        this.Warrior3.setContentAreaFilled(false);
        this.Warrior3.setBorderPainted(false);
        this.Warrior4.setOpaque(false);
        this.Warrior4.setContentAreaFilled(false);
        this.Warrior4.setBorderPainted(false);
        this.Warrior5.setOpaque(false);
        this.Warrior5.setContentAreaFilled(false);
        this.Warrior5.setBorderPainted(false);
        this.Warrior6.setOpaque(false);
        this.Warrior6.setContentAreaFilled(false);
        this.Warrior6.setBorderPainted(false);
        this.Warrior7.setOpaque(false);
        this.Warrior7.setContentAreaFilled(false);
        this.Warrior7.setBorderPainted(false);
        this.Warrior8.setOpaque(false);
        this.Warrior8.setContentAreaFilled(false);
        this.Warrior8.setBorderPainted(false);
        
        this.FightButton.setOpaque(false);
        this.FightButton.setContentAreaFilled(false);
        this.FightButton.setBorderPainted(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        FightHoverLabel = new javax.swing.JLabel();
        GoldLabel = new javax.swing.JLabel();
        CantGoldLabel = new javax.swing.JLabel();
        Warrior1 = new javax.swing.JButton();
        Warrior2 = new javax.swing.JButton();
        Warrior3 = new javax.swing.JButton();
        Warrior4 = new javax.swing.JButton();
        Warrior5 = new javax.swing.JButton();
        Warrior6 = new javax.swing.JButton();
        Warrior7 = new javax.swing.JButton();
        Warrior8 = new javax.swing.JButton();
        FightButton = new javax.swing.JButton();
        LevelLabel = new javax.swing.JLabel();
        ArmyCapacityLabel = new javax.swing.JLabel();
        CantLvlLabel = new javax.swing.JLabel();
        CanrArmyLabel = new javax.swing.JLabel();
        BackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Title.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\Images\\Select Your Army.png")); // NOI18N
        getContentPane().add(Title);
        Title.setBounds(350, 20, 670, 140);

        FightHoverLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\Images\\FightHover.png")); // NOI18N
        getContentPane().add(FightHoverLabel);
        FightHoverLabel.setBounds(700, 640, 180, 94);

        GoldLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\Images\\Gold.png")); // NOI18N
        getContentPane().add(GoldLabel);
        GoldLabel.setBounds(1100, 140, 170, 90);

        CantGoldLabel.setFont(new java.awt.Font("Pristina", 1, 48)); // NOI18N
        CantGoldLabel.setForeground(new java.awt.Color(0, 0, 0));
        CantGoldLabel.setText("0");
        getContentPane().add(CantGoldLabel);
        CantGoldLabel.setBounds(1280, 140, 80, 70);

        Warrior1.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\DragonAssets\\DragonAttacking.gif")); // NOI18N
        Warrior1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Warrior1ActionPerformed(evt);
            }
        });
        getContentPane().add(Warrior1);
        Warrior1.setBounds(360, 210, 180, 120);

        Warrior2.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\ArcherAssets\\ArcherAttack.gif")); // NOI18N
        Warrior2.setToolTipText("Isaaaaaa sea necio banano");
        getContentPane().add(Warrior2);
        Warrior2.setBounds(130, 210, 160, 120);

        Warrior3.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\BearAssets\\BearAttack.gif")); // NOI18N
        Warrior3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Warrior3ActionPerformed(evt);
            }
        });
        getContentPane().add(Warrior3);
        Warrior3.setBounds(620, 210, 170, 120);
        getContentPane().add(Warrior4);
        Warrior4.setBounds(370, 420, 170, 130);

        Warrior5.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\GolemAssets\\GolemAttack.gif")); // NOI18N
        getContentPane().add(Warrior5);
        Warrior5.setBounds(130, 420, 155, 129);

        Warrior6.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\KnightSkeletonAssets\\KnightSAttack.gif")); // NOI18N
        getContentPane().add(Warrior6);
        Warrior6.setBounds(870, 210, 170, 130);
        getContentPane().add(Warrior7);
        Warrior7.setBounds(620, 420, 170, 130);
        getContentPane().add(Warrior8);
        Warrior8.setBounds(870, 420, 170, 130);

        FightButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\Images\\Fight.png")); // NOI18N
        FightButton.setActionCommand("");
        FightButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FightButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FightButtonMouseExited(evt);
            }
        });
        FightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FightButtonActionPerformed(evt);
            }
        });
        getContentPane().add(FightButton);
        FightButton.setBounds(690, 640, 210, 100);

        LevelLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\Images\\Level.png")); // NOI18N
        getContentPane().add(LevelLabel);
        LevelLabel.setBounds(1090, 270, 190, 90);

        ArmyCapacityLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\Images\\ArmyCapacity.png")); // NOI18N
        getContentPane().add(ArmyCapacityLabel);
        ArmyCapacityLabel.setBounds(10, 660, 460, 90);

        CantLvlLabel.setFont(new java.awt.Font("Pristina", 1, 48)); // NOI18N
        CantLvlLabel.setForeground(new java.awt.Color(0, 0, 0));
        CantLvlLabel.setText("0");
        getContentPane().add(CantLvlLabel);
        CantLvlLabel.setBounds(1280, 280, 80, 70);

        CanrArmyLabel.setFont(new java.awt.Font("Pristina", 1, 48)); // NOI18N
        CanrArmyLabel.setForeground(new java.awt.Color(0, 0, 0));
        CanrArmyLabel.setText("0");
        getContentPane().add(CanrArmyLabel);
        CanrArmyLabel.setBounds(480, 670, 80, 70);

        BackgroundLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\Images\\ArmySelectionBackground.jpg")); // NOI18N
        BackgroundLabel.setAlignmentY(0.0F);
        getContentPane().add(BackgroundLabel);
        BackgroundLabel.setBounds(0, 0, 1370, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Warrior1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Warrior1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Warrior1ActionPerformed

    private void Warrior3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Warrior3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Warrior3ActionPerformed

    private void FightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FightButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FightButtonActionPerformed

    private void FightButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FightButtonMouseEntered
        this.FightHoverLabel.setVisible(true);
    }//GEN-LAST:event_FightButtonMouseEntered

    private void FightButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FightButtonMouseExited
        this.FightHoverLabel.setVisible(false);
    }//GEN-LAST:event_FightButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArmySelectionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArmySelectionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArmySelectionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArmySelectionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArmySelectionWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ArmyCapacityLabel;
    private javax.swing.JLabel BackgroundLabel;
    public javax.swing.JLabel CanrArmyLabel;
    public javax.swing.JLabel CantGoldLabel;
    public javax.swing.JLabel CantLvlLabel;
    public javax.swing.JButton FightButton;
    private javax.swing.JLabel FightHoverLabel;
    private javax.swing.JLabel GoldLabel;
    private javax.swing.JLabel LevelLabel;
    private javax.swing.JLabel Title;
    public javax.swing.JButton Warrior1;
    public javax.swing.JButton Warrior2;
    public javax.swing.JButton Warrior3;
    public javax.swing.JButton Warrior4;
    public javax.swing.JButton Warrior5;
    public javax.swing.JButton Warrior6;
    public javax.swing.JButton Warrior7;
    public javax.swing.JButton Warrior8;
    // End of variables declaration//GEN-END:variables
}
