/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JFrame;


/**
 *
 * @author nacho
 */
public class MainWindow extends javax.swing.JFrame {
    /**
     * Creates new form MainWindow
     */
    
    public MainWindow() {
        initComponents();
        this.jButton1.setOpaque(false);
        this.jButton1.setContentAreaFilled(false);
        this.jButton1.setBorderPainted(false);
        this.EnterTheSeaLabel.setVisible(false);
        this.jLabel1.setVisible(false);
        this.NewUserButton.setOpaque(false);
        this.NewUserButton.setContentAreaFilled(false);
        this.NewUserButton.setBorderPainted(false);
        this.Administrate.setOpaque(false);
        this.Administrate.setContentAreaFilled(false);
        this.Administrate.setBorderPainted(false);
        this.AdministrateLabel.setVisible(false);

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        EnterTheSeaLabel = new javax.swing.JLabel();
        UsernameLable = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PasswordTextField = new javax.swing.JPasswordField();
        UsernameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        NewUserButton = new javax.swing.JButton();
        AdministrateLabel = new javax.swing.JLabel();
        Administrate = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 911));
        getContentPane().setLayout(null);

        TitleLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\Images\\Title.png")); // NOI18N
        getContentPane().add(TitleLabel);
        TitleLabel.setBounds(310, 90, 540, 140);

        EnterTheSeaLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\Images\\EnterButtonHover.png")); // NOI18N
        getContentPane().add(EnterTheSeaLabel);
        EnterTheSeaLabel.setBounds(240, 490, 540, 130);

        UsernameLable.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\Images\\Username.png")); // NOI18N
        getContentPane().add(UsernameLable);
        UsernameLable.setBounds(220, 310, 230, 80);

        PasswordLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\Images\\Password.png")); // NOI18N
        getContentPane().add(PasswordLabel);
        PasswordLabel.setBounds(220, 430, 240, 60);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\Images\\EnterButton.png")); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 500, 540, 110);

        PasswordTextField.setBackground(new java.awt.Color(0, 122, 126));
        PasswordTextField.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        PasswordTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        PasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordTextField);
        PasswordTextField.setBounds(450, 430, 230, 40);

        UsernameTextField.setBackground(new java.awt.Color(0, 122, 126));
        UsernameTextField.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        UsernameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        UsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameTextField);
        UsernameTextField.setBounds(450, 330, 230, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\Images\\NewUserHover.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 620, 200, 50);

        NewUserButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\Images\\NewUser.png")); // NOI18N
        NewUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewUserButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NewUserButtonMouseExited(evt);
            }
        });
        NewUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewUserButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NewUserButton);
        NewUserButton.setBounds(380, 620, 230, 50);

        AdministrateLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\Images\\AdministrateHover.png")); // NOI18N
        getContentPane().add(AdministrateLabel);
        AdministrateLabel.setBounds(813, 30, 270, 60);

        Administrate.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\Images\\Administrate.png")); // NOI18N
        Administrate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdministrateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdministrateMouseExited(evt);
            }
        });
        getContentPane().add(Administrate);
        Administrate.setBounds(810, 20, 280, 85);

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\Images\\MainWindowBackground.jpg")); // NOI18N
        Background.setText("jLabel1");
        Background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BackgroundMouseMoved(evt);
            }
        });
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1100, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackgroundMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_BackgroundMouseMoved

    private void PasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextFieldActionPerformed

    private void UsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println(this.UsernameTextField.getText());
        System.out.println(this.PasswordTextField.getText());

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        this.EnterTheSeaLabel.setVisible(true);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        this.EnterTheSeaLabel.setVisible(false);
    }//GEN-LAST:event_jButton1MouseExited

    private void NewUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewUserButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NewUserButtonActionPerformed

    private void NewUserButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserButtonMouseEntered
        // TODO add your handling code here:
        this.jLabel1.setVisible(true);
    }//GEN-LAST:event_NewUserButtonMouseEntered

    private void NewUserButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewUserButtonMouseExited
        // TODO add your handling code here:
        this.jLabel1.setVisible(false);
    }//GEN-LAST:event_NewUserButtonMouseExited

    private void AdministrateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdministrateMouseEntered
        this.AdministrateLabel.setVisible(true);
    }//GEN-LAST:event_AdministrateMouseEntered

    private void AdministrateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdministrateMouseExited
        this.AdministrateLabel.setVisible(false);
    }//GEN-LAST:event_AdministrateMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame window = new MainWindow();
                window.setSize(1100, 800);
                window.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Administrate;
    private javax.swing.JLabel AdministrateLabel;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel EnterTheSeaLabel;
    public javax.swing.JButton NewUserButton;
    private javax.swing.JLabel PasswordLabel;
    public javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel UsernameLable;
    public javax.swing.JTextField UsernameTextField;
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
