/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import javax.swing.JOptionPane;


/**
 *
 * @author nacho
 */
public class MenuUser extends javax.swing.JFrame {

    /**
     * Creates new form MenuUser
     */
    public MenuUser() {
        initComponents();
        this.setSize(1244,827);
        this.ContinueJourneyButton.setOpaque(false);
        this.ContinueJourneyButton.setContentAreaFilled(false);
        this.ContinueJourneyButton.setBorderPainted(false);
        this.ContinueJourneyLabel.setVisible(false);
        this.NewJourneyLabel.setVisible(false);
        this.NewJourneyButton.setOpaque(false);
        this.NewJourneyButton.setContentAreaFilled(false);
        this.NewJourneyButton.setBorderPainted(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomeLabel = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        NewJourneyLabel = new javax.swing.JLabel();
        NewJourneyButton = new javax.swing.JButton();
        ContinueJourneyLabel = new javax.swing.JLabel();
        ContinueJourneyButton = new javax.swing.JButton();
        BackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        WelcomeLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\Images\\WelcomePirate.png")); // NOI18N
        getContentPane().add(WelcomeLabel);
        WelcomeLabel.setBounds(10, 40, 280, 100);

        UsernameTextField.setEditable(false);
        UsernameTextField.setBackground(new java.awt.Color(0, 59, 60));
        UsernameTextField.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        UsernameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        UsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameTextField);
        UsernameTextField.setBounds(300, 50, 260, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\Images\\Where now.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 170, 540, 70);

        NewJourneyLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\Images\\NewJourneyHover.png")); // NOI18N
        getContentPane().add(NewJourneyLabel);
        NewJourneyLabel.setBounds(220, 380, 930, 100);

        NewJourneyButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\Images\\NewJourney.png")); // NOI18N
        NewJourneyButton.setToolTipText("Ready to conquer the seas?");
        NewJourneyButton.setOpaque(false);
        NewJourneyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewJourneyButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NewJourneyButtonMouseExited(evt);
            }
        });
        NewJourneyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewJourneyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NewJourneyButton);
        NewJourneyButton.setBounds(210, 370, 910, 120);

        ContinueJourneyLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\Images\\ContinueJourneyHover.png")); // NOI18N
        getContentPane().add(ContinueJourneyLabel);
        ContinueJourneyLabel.setBounds(350, 590, 590, 100);

        ContinueJourneyButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\Images\\ContinueJourney.png")); // NOI18N
        ContinueJourneyButton.setToolTipText("Continue your epic adventure!");
        ContinueJourneyButton.setOpaque(false);
        ContinueJourneyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContinueJourneyButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ContinueJourneyButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ContinueJourneyButtonMouseExited(evt);
            }
        });
        ContinueJourneyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueJourneyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ContinueJourneyButton);
        ContinueJourneyButton.setBounds(300, 580, 680, 120);

        BackgroundLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\nacho\\Desktop\\Proyectos\\Java\\The-War-of-Inheritance\\ShadowsOfPiltover\\src\\main\\java\\View\\Images\\UserMenuBackground.jpg")); // NOI18N
        getContentPane().add(BackgroundLabel);
        BackgroundLabel.setBounds(0, 0, 1240, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextFieldActionPerformed

    private void NewJourneyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewJourneyButtonActionPerformed
    }//GEN-LAST:event_NewJourneyButtonActionPerformed

    private void NewJourneyButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewJourneyButtonMouseEntered
        // TODO add your handling code here:
        NewJourneyLabel.setVisible(true);
    }//GEN-LAST:event_NewJourneyButtonMouseEntered

    private void NewJourneyButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewJourneyButtonMouseExited
        // TODO add your handling code here:
        NewJourneyLabel.setVisible(false);

    }//GEN-LAST:event_NewJourneyButtonMouseExited

    private void ContinueJourneyButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContinueJourneyButtonMouseEntered
        // TODO add your handling code here:
        ContinueJourneyLabel.setVisible(true);

    }//GEN-LAST:event_ContinueJourneyButtonMouseEntered

    private void ContinueJourneyButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContinueJourneyButtonMouseExited
        // TODO add your handling code here:
        ContinueJourneyLabel.setVisible(false);
    }//GEN-LAST:event_ContinueJourneyButtonMouseExited

    private void ContinueJourneyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContinueJourneyButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ContinueJourneyButtonMouseClicked

    private void ContinueJourneyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueJourneyButtonActionPerformed
       
    }//GEN-LAST:event_ContinueJourneyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLabel;
    public javax.swing.JButton ContinueJourneyButton;
    private javax.swing.JLabel ContinueJourneyLabel;
    public javax.swing.JButton NewJourneyButton;
    private javax.swing.JLabel NewJourneyLabel;
    public javax.swing.JTextField UsernameTextField;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
